### ISSUE TITLE
Error while view blog entry

### ISSUE THREAD

**Issue by LloydS42** [Universal-Omega/SimpleBlogPage#30]
Installed SimpleBlogPage today:
- Gentoo-Linux x64
- Apache/2.4.51 (Unix)
- php-fpm7.4
- PostgreSQL 12.9
- MediaWiki 1.36.2

Can not view created Blog-Entrys. Allways the following error occurs:

`MediaWiki internal error.

Original exception: [YZpBqclFSyOcHC6qSkRN3AAAAMo] /wiki/index.php?title=User_blog:Ashley/Lorem_Ipsum Error: Call to a member function getId() on bool
Backtrace:
from /var/www/mediawiki/mediawiki-1.36.2/extensions/SimpleBlogPage/includes/SimpleBlogPage.php(35)
#0 /var/www/mediawiki/mediawiki-1.36.2/extensions/SimpleBlogPage/includes/SimpleBlogPage.php(26): SimpleBlogPage->getAuthor()
#1 /var/www/mediawiki/mediawiki-1.36.2/extensions/SimpleBlogPage/includes/SimpleBlogPageHooks.php(83): SimpleBlogPage->__construct(Title)
#2 /var/www/mediawiki/mediawiki-1.36.2/includes/HookContainer/HookContainer.php(338): SimpleBlogPageHooks::onArticleFromTitle(Title, NULL, RequestContext)
#3 /var/www/mediawiki/mediawiki-1.36.2/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#4 /var/www/mediawiki/mediawiki-1.36.2/includes/HookContainer/HookRunner.php(757): MediaWiki\HookContainer\HookContainer->run(string, array)
#5 /var/www/mediawiki/mediawiki-1.36.2/includes/page/Article.php(157): MediaWiki\HookContainer\HookRunner->onArticleFromTitle(Title, NULL, RequestContext)
#6 /var/www/mediawiki/mediawiki-1.36.2/includes/page/Article.php(183): Article::newFromTitle(Title, RequestContext)
#7 /var/www/mediawiki/mediawiki-1.36.2/includes/actions/Action.php(177): Article::newFromWikiPage(WikiPage, RequestContext)
#8 /var/www/mediawiki/mediawiki-1.36.2/includes/MediaWiki.php(171): Action::getActionName(RequestContext)
#9 /var/www/mediawiki/mediawiki-1.36.2/includes/MediaWiki.php(875): MediaWiki->getAction()
#10 /var/www/mediawiki/mediawiki-1.36.2/includes/MediaWiki.php(546): MediaWiki->main()
#11 /var/www/mediawiki/mediawiki-1.36.2/index.php(53): MediaWiki->run()
#12 /var/www/mediawiki/mediawiki-1.36.2/index.php(46): wfIndexMain()
#13 {main}

Exception caught inside exception handler: [YZpBqclFSyOcHC6qSkRN3AAAAMo] /wiki/index.php?title=User_blog:Ashley/Lorem_Ipsum Error: Call to a member function getId() on bool
Backtrace:
from /var/www/mediawiki/mediawiki-1.36.2/extensions/SimpleBlogPage/includes/SimpleBlogPage.php(35)
#0 /var/www/mediawiki/mediawiki-1.36.2/extensions/SimpleBlogPage/includes/SimpleBlogPage.php(26): SimpleBlogPage->getAuthor()
#1 /var/www/mediawiki/mediawiki-1.36.2/extensions/SimpleBlogPage/includes/SimpleBlogPageHooks.php(83): SimpleBlogPage->__construct(Title)
#2 /var/www/mediawiki/mediawiki-1.36.2/includes/HookContainer/HookContainer.php(338): SimpleBlogPageHooks::onArticleFromTitle(Title, NULL, SkinVector)
#3 /var/www/mediawiki/mediawiki-1.36.2/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#4 /var/www/mediawiki/mediawiki-1.36.2/includes/HookContainer/HookRunner.php(757): MediaWiki\HookContainer\HookContainer->run(string, array)
#5 /var/www/mediawiki/mediawiki-1.36.2/includes/page/Article.php(157): MediaWiki\HookContainer\HookRunner->onArticleFromTitle(Title, NULL, SkinVector)
#6 /var/www/mediawiki/mediawiki-1.36.2/includes/page/Article.php(183): Article::newFromTitle(Title, SkinVector)
#7 /var/www/mediawiki/mediawiki-1.36.2/includes/actions/Action.php(177): Article::newFromWikiPage(WikiPage, SkinVector)
#8 /var/www/mediawiki/mediawiki-1.36.2/includes/skins/SkinTemplate.php(176): Action::getActionName(SkinVector)
#9 /var/www/mediawiki/mediawiki-1.36.2/includes/skins/SkinMustache.php(185): SkinTemplate->wrapHTML(Title, string)
#10 /var/www/mediawiki/mediawiki-1.36.2/skins/Vector/includes/SkinVector.php(177): SkinMustache->getTemplateData()
#11 /var/www/mediawiki/mediawiki-1.36.2/includes/skins/SkinMustache.php(136): SkinVector->getTemplateData()
#12 /var/www/mediawiki/mediawiki-1.36.2/includes/skins/SkinTemplate.php(146): SkinMustache->generateHTML()
#13 /var/www/mediawiki/mediawiki-1.36.2/includes/OutputPage.php(2634): SkinTemplate->outputPage()
#14 /var/www/mediawiki/mediawiki-1.36.2/includes/exception/MWExceptionRenderer.php(147): OutputPage->output()
#15 /var/www/mediawiki/mediawiki-1.36.2/includes/exception/MWExceptionRenderer.php(66): MWExceptionRenderer::reportHTML(Error)
#16 /var/www/mediawiki/mediawiki-1.36.2/includes/exception/MWExceptionHandler.php(106): MWExceptionRenderer::output(Error, integer)
#17 /var/www/mediawiki/mediawiki-1.36.2/includes/exception/MWExceptionHandler.php(185): MWExceptionHandler::report(Error)
#18 /var/www/mediawiki/mediawiki-1.36.2/includes/MediaWiki.php(568): MWExceptionHandler::handleException(Error, string)
#19 /var/www/mediawiki/mediawiki-1.36.2/index.php(53): MediaWiki->run()
#20 /var/www/mediawiki/mediawiki-1.36.2/index.php(46): wfIndexMain()
#21 {main}`

**Comment by Universal-Omega** [comment]
Hello! Thanks for bringing this up. If it is possible can you please tell me the output of `Title::newFromText( 'User_blog:Ashley/Lorem_Ipsum' )->getRootText()`, `Title::newFromText( 'User_blog:Ashley/Lorem_Ipsum' )`, `Title::newFromText( 'User_blog:Ashley' )`, and `User::newFromName( 'Ashley' )` using eval.php or shell.php? If it isn't possible I can figure it out without that'd just make it easier. Also, can you confirm the user account, `Ashley` exists on your wiki? If it doesn't that is why the error is given, and I can probably add checks for non-existent users. Thanks!

**Comment by Universal-Omega** [comment]
Actually this is the same issue as #27. Closing issue and I'll merge the PR that is open to fix that once I test it a bit later.

**Comment by LloydS42** [comment]
Yes, Ashley exists and wrote article. In the hurry, I don't understand the changes you made, but everything is fine now. Thank you!
